services:
  postgres:
    image: postgres:18-alpine
    container_name: mono_f7_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mono_f7
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mono_f7"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
